CREATE TABLE "Currencies" (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`ShortName`	TEXT NOT NULL UNIQUE,
	`Name`	TEXT NOT NULL UNIQUE,
	`Comment`	TEXT
);

CREATE TABLE "Accounts" (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`Name`	TEXT NOT NULL UNIQUE,
	`CurrencyId`	INTEGER NOT NULL,
	`Amount`	REAL NOT NULL,
	`Comment`	TEXT,
	FOREIGN KEY(`CurrencyId`) REFERENCES Currencies ( Id )
);

CREATE TABLE "ExpenseCategories" (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`Name`	TEXT NOT NULL UNIQUE,
	`Type`	INTEGER NOT NULL,
	`Comment`	TEXT
);

CREATE TABLE "ExpenseItems" (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`Name`	TEXT NOT NULL,
	`ExpenseCategoryId`	INTEGER NOT NULL,
	`Comment`	TEXT,
	FOREIGN KEY(`ExpenseCategoryId`) REFERENCES ExpenseCategories ( Id )
);

CREATE TABLE "Users" (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`Login`	TEXT NOT NULL UNIQUE,
	`PasswordHash`	TEXT NOT NULL,
	`FirstName`	TEXT,
	`LastName`	TEXT,
	`Email`	TEXT,
	`Comment`	TEXT
);

CREATE TABLE "Operations" (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`OperationTime`	REAL NOT NULL,
	`UserId`	INTEGER NOT NULL,
	`AccountId`	INTEGER NOT NULL,
	`Amount`	REAL NOT NULL,
	`ExpenseItemId`	INTEGER NOT NULL,
	`Comment`	TEXT,
	FOREIGN KEY(`UserId`) REFERENCES Users ( Id ),
	FOREIGN KEY(`AccountId`) REFERENCES Accounts ( Id ),
	FOREIGN KEY(`ExpenseItemId`) REFERENCES ExpenseItems ( Id )
);